name: Metrics-2

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Hacker-Style GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-hacker.svg

          theme: dark
          config_timezone: Asia/Seoul
          config_order: base.header, base.activity, plugin.languages, plugin.isocalendar, plugin.achievements, plugin.followup
          config_twemoji: yes
          config_display: large

          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 0%
          plugin_languages_colors: hacker

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          plugin_followup: yes

          plugin_calendar: yes

          plugin_stars: yes
